name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: ap-southeast-1
  EB_ENVIRONMENT_NAME: carrentalweb-prod
  EB_APPLICATION_NAME: CarRentalWeb

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn test
      
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Generate deployment package
      run: |
        mkdir -p .ebextensions
        cp -r target/CarRentalWeb-1.0.0.jar ./
        # Update VPC configuration with actual IDs
        sed -i 's/vpc-xxxxxxxxx/${{ secrets.VPC_ID }}/g' .ebextensions/02_vpc.config
        sed -i 's/subnet-xxxxxxxxx/${{ secrets.PUBLIC_SUBNET_1 }},${{ secrets.PUBLIC_SUBNET_2 }}/g' .ebextensions/02_vpc.config
        sed -i 's/sg-xxxxxxxxx/${{ secrets.ELASTIC_BEANSTALK_SG }}/g' .ebextensions/02_vpc.config
        # Create deployment package
        zip -r deploy.zip . -x "*.git*" "target/*" "src/*" "pom.xml" ".mvn/*" "mvnw*" "README.md" "aws-security-groups.md"
        
    - name: Show deployment info
      run: |
        echo "Deploying to AWS Elastic Beanstalk..."
        echo "Application: ${{ env.EB_APPLICATION_NAME }}"
        echo "Environment: ${{ env.EB_ENVIRONMENT_NAME }}"
        echo "Region: ${{ env.AWS_REGION }}"
        echo "VPC ID: ${{ secrets.VPC_ID }}"
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        region: ${{ env.AWS_REGION }}
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        wait_for_deployment: true 